---
- name: "Set up Raspberry Pi for Compute"
  hosts: localhost
  connection: local
  tasks:

  - name: "Enable dwc2 module"
    lineinfile:
      path: /boot/cmdline.txt
      line: modules-load=dwc2
      create: yes
    become: yes
