---
- name: "Set up Raspberry Pi for Compute"
  hosts: localhost
  connection: local
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:

  - name: "Enable dwc2 module"
    lineinfile:
      path: /boot/firmware/cmdline.txt
      line: modules-load=dwc2
      create: yes
    become: yes

  - name: "Enable dwc2"
    lineinfile:
      path: /boot/firmware/usercfg.txt
      regex: '^dtoverlay='
      line: dtoverlay=dwc2
      create: yes
    become: yes

  - name: "Disable serial console"
    lineinfile:
      path: /boot/firmware/usercfg.txt  
      regex: '^enable_uart='
      line: enable_uart=0
      create: yes
    become: yes

  - name: "Set Dnsmasq port"
    become: yes
    lineinfile:
      path: /etc/dnsmasq.conf
      regex: '^port='
      line: port=0

  - name: "Add libcomposite kernel module"
    become: yes
    lineinfile:
      path: /etc/modules
      line: libcomposite

  - name: "Enable libcomposite kernel module"
    become: yes
    modprobe:
      name: libcomposite

  - name: "Copy the USB setup script"
    become: yes
    copy:
      src: ipad-usb.sh
      dest: /usr/local/bin/ipad-usb.sh
      owner: root
      group: root
      mode: '0700'

  - name: Set the shell to ZSH"
    become: yes
    user:
      name: "{{ the_user }}"
      shell: /bin/zsh
