---
- name: "Set up Raspberry Pi for Compute"
  hosts: localhost
  connection: local
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:

  - name: "Enable dwc2 module"
    lineinfile:
      path: /boot/firmware/cmdline.txt
      line: modules-load=dwc2
      create: yes
    become: yes

  - name: "Enable dwc2"
    lineinfile:
      path: /boot/firmware/usercfg.txt
      regex: '^dtoverlay='
      line: dtoverlay=dwc2
      create: yes
    become: yes

  - name: "Disable serial console"
    lineinfile:
      path: /boot/firmware/usercfg.txt  
      regex: '^enable_uart='
      line: enable_uart=0
      create: yes
    become: yes

  - name: "Set Dnsmasq port"
    become: yes
    lineinfile:
      path: /etc/dnsmasq.conf
      regex: '^port='
      line: port=0

  - name: "Add libcomposite kernel module"
    become: yes
    lineinfile:
      path: /etc/modules
      line: libcomposite

  - name: "Enable libcomposite kernel module"
    become: yes
    modprobe:
      name: libcomposite

  - name: "USB DNS configuration"
    become: yes
    copy:
      src: usb
      dest: /etc/dnsmasq.d/usb
      owner: root
      group: root

  - name: "USB network interface"
    become: yes
    copy:
      src: usb0
      dest: /etc/network/interfaces.d/usb0
      owner: root
      group: root

  - name: "Copy the USB setup script"
    become: yes
    copy:
      src: ipad-usb.sh
      dest: /usr/local/bin/ipad-usb.sh
      owner: root
      group: root
      mode: '0700'

  - name: "Create the iPad USB service"
    become: yes
    copy:
      src: ipad-usb.service
      dest: /etc/systemd/system/ipad-usb.service
      owner: root
      group: root

  - name: "Enable the iPad USB service"
    become: yes
    systemd:
      name: ipad-usb
      enabled: yes
      daemon_reload: yes

  - name: "Set the shell to ZSH"
    become: yes
    user:
      name: "{{ the_user }}"
      shell: /bin/zsh

  - name: "Disable MOTD"
    become: yes
    lineinfile:
      path: /etc/default/motd-news
      regex: '^ENABLED='
      line: ENABLED=0

  - name: "Copy the SMB share configuration"
    become: yes
    copy:
      src: smb-compute-home.conf
      dest: /etc/samba/smb-compute-home.conf
      owner: root
      group: root

  - name: "Enable SMB share"
    lineinfile:
      path: /etc/samba/smb.conf
      line: include = /etc/samba/smb-compute-home.conf
      create: yes
    become: yes
    notify: Restart Samba

  - name: "Get the current Samba users"
    shell: "pdbedit -L | sed 's/:.*$//'"
    become: yes
    register: samba_users
    changed_when: no

  - name: "Add SMB user"
    shell: "printf 'password\npassword\n' | smbpasswd -a ubuntu"
    become: yes
    when: not "ubuntu" in samba_users.stdout_lines
    notify: Restart Samba

  handlers:

  - name: Restart Samba
    become: yes
    service:
      name: smbd
      state: restarted
