#!/bin/bash

set -e

should_update=false
should_run_shell=false

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    --update)
    should_update=true
    shift
    ;;
    --shell)
    should_run_shell=true
    shift
    ;;
    *)
    POSITIONAL+=("$1")
    shift
    ;;
esac
done
set -- "${POSITIONAL[@]}"

should_log_wait_event=true
while (! docker stats --no-stream > /dev/null 2>&1 ); do
    if [ "$should_log_wait_event" = true ] ; then
        >&2 echo "Waiting for Docker..."
        should_log_wait_event=false
    fi
    sleep 2
done

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export WORKING_DIR="$PWD"
if  [ "$should_update" = true ] ; then
    docker-compose -f "$DIR/docker-compose.yaml" build
fi

if  [ "$should_run_shell" = true ] ; then
    docker-compose -f "$DIR/docker-compose.yaml" run shell
    exit
fi

docker-compose -f "$DIR/docker-compose.yaml" run command "$@"
